### ISSUE TITLE
Python 3.10.x fails to find `ssl` with openssl `3.x`

### ISSUE THREAD

**Issue by bysnack** [lumicks/embedded_python#36]
Spotted on Ubuntu 23.04

Steps to reproduce:

1. Go to `test_package/conanfile.py`
2. Change the `embedded_python:version` default option to `3.10.x`
3. Run `conan create . lumicks/stable --build=missing`
4. See it fail
```
embedded_python/1.8.0@lumicks/stable (test package): Running test()
3.10.0 (default, Aug 23 2023, 16:29:28) [GCC 12.3.0]
Traceback (most recent call last):
  File "/home/andres/lumicks/embedded_python/test_package/baseline/test.py", line 5, in <module>
    import ssl
  File "lib/python3.10/ssl.py", line 98, in <module>
ModuleNotFoundError: No module named '_ssl'
```

Note that overriding the openssl requirement to `1.1.x` actually works properly.

**Comment by dean0x7d** [comment]
Seems like 3.10 is only partially compatible. It makes sense since they only started shipping openssl v3 in pre-built packages with 3.11. I've updated the requirement in #37.
